package com.html5parser.SimplestTreeParser;

import java.util.List;

import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.ParserConfigurationException;

import org.w3c.dom.Document;

public class TreeConstructor {

	/**
	 * Construct a tree from a list of Tokens.
	 * 
	 * @param tokens
	 *            The list of tokens generated by the tokenizer.
	 * @return Document a DOM object.
	 * @throws Exception
	 *             invalid token.
	 */
	public Document ConstructDOM(List<Token> tokens) {

		Document doc = null;
		try {
			DocumentBuilderFactory dbf = DocumentBuilderFactory.newInstance();
			DocumentBuilder builder = dbf.newDocumentBuilder();
			doc = builder.newDocument();
		} catch (ParserConfigurationException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		return doc;
	}

}